name: AnotherTPA
main: com.leocth.anothertpa.AnotherTPA
version: 1.3.0
commands:
   atpa:
      description: Request to teleport to a player.
      usage: /atpa [player]
      permission: anothertpa.tpa
      permission-message: You don't have the permission to access this command.
   atpac:
      description: Accept a pending teleport request.
      usage: /atpac [player]
      permission: anothertpa.tpa
      permission-message: You don't have the permission to access this command.
   atpad:
      description: Deny a pending teleport request.
      usage: /atpad [player]
      permission: anothertpa.tpa
      permission-message: You don't have the permission to access this command.
   atpah:
      description: Request a player to teleport to you.
      usage: /atpah [player]
      permission: anothertpa.tpa
      permission-message: You don't have the permission to access this command.